
train: C:/Users/ASUS/Desktop/PROYECTO_OCR/PDSeI-2023-SofiaMoreno/PROYECTO_OCR/Post-entrenamiento/Colores_semaforo/Data/train
val: C:/Users/ASUS/Desktop/PROYECTO_OCR/PDSeI-2023-SofiaMoreno/PROYECTO_OCR/Post-entrenamiento/Colores_semaforo/Data/val

nc: 3

names: 
  
  1: Luz_Verde
  2: Luz_Roja
  3: Luz_Amarilla
