
train: D:\Procesamiento\PDSeI-2023-SofiaMoreno\PROYECTO_OCR\Data\Train
val: D:\Procesamiento\PDSeI-2023-SofiaMoreno\PROYECTO_OCR\Data\Val

names: 
  0: Bicycle
  1: Building
  2: Car
  3: Cat
  4: Dog
  5: Person
  6: Motorcycle
  7: "Street light"
  8: "Traffic light"
  9: "Traffic sign"
  10: Tree
