
train: C:/Users/ASUS/Desktop/PROYECTO_OCR/PDSeI-2023-SofiaMoreno/PROYECTO_OCR/Data/train
val: C:/Users/ASUS/Desktop/PROYECTO_OCR/PDSeI-2023-SofiaMoreno/PROYECTO_OCR/Data/val

nc: 11

names: 
  0: Bicicleta
  1: Edificio
  2: Coche
  3: Gato
  4: Perro
  5: Persona
  6: Motocicleta
  7: Poste
  8: Semaforo
  9: Señales
  10: Árbol
